language: generic
addons:
  ssh_known_hosts: ec2-52-206-3-72.compute-1.amazonaws.com
before_install:
- openssl aes-256-cbc -K $encrypted_4b7e77f3c37e_key -iv $encrypted_4b7e77f3c37e_iv
  -in coyote.enc -out coyote -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/coyote
- ssh-add /tmp/coyote
deploy:
  provider: script
  skip_cleanup: true
  script: sh ./deploy.sh
