language: generic

addons:
  ssh_known_hosts: ec2-52-206-3-72.compute-1.amazonaws.com
before_install:
- openssl aes-256-cbc -K $encrypted_2eb2d4c81e92_key -iv $encrypted_2eb2d4c81e92_iv -in coyote.enc -out /tmp/coyote -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/coyote
- ssh-add /tmp/coyote

deploy:
  provider: script
  skip_cleanup: true
  script: sh ./deploy.sh